name: elisha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.0.6
  simple_animations: ^3.0.0
  introduction_screen: ^3.0.1
  speech_to_text: ^5.4.3

  platform: ^3.1.0
  # UI
  # UI
  canton_design_system:
    git:
      url: https://github.com/5ran6/design_system.git
      ref: master
  font_awesome_flutter: ^9.2.0
  line_awesome_flutter: ^2.0.0
  vertical_card_pager: ^1.5.0
  cached_network_image: ^3.0.0
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0
  flutter_native_timezone: ^2.0.0

  flutter_riverpod: ^0.14.0+3
  shimmer: ^2.0.0
  uuid: ^3.0.6

  # API
  dio: ^4.0.0
  universal_html: ^2.0.8

  # Firebase
  firebase_core: 2.13.1
  firebase_auth: ^4.6.2
  firebase_analytics: ^10.0.1
  firebase_crashlytics: ^3.0.1
  firebase_performance: ^0.9.0+1
  firebase_dynamic_links: ^5.0.1

  # Ads

  # Storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # Third Party OAuth
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^3.3.0

  # Other
  intl: ^0.17.0
  crypto: ^3.0.1
  url_launcher: ^6.0.9
  youtube_player_flutter: ^8.0.0
  flutter_linkify: ^5.0.2
  flutter_launcher_icons: ^0.9.1
  flutter_phoenix: ^1.0.0
  page_transition: ^2.0.2
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  youtube_player_iframe: ^2.2.2
  flutter_staggered_grid_view: ^0.4.0
  reference_parser: ^3.0.0
  share_plus: ^2.0.1
  http: ^0.13.4
  provider: ^6.0.3
  flutter_dnd: ^0.1.4+1
  flutter_alarm_clock: ^0.0.2
  flutter_background_service: ^2.1.3
  fluttertoast: ^8.0.9
  collection: ^1.14.13
  flowder:
    git:
      url: https://github.com/Harsh223/flowder.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/SecretPlace(1024).png"

  flutter_native_splash: ^1.2.1
  import_sorter: ^4.6.0
  dio: ^4.0.6
  intl: ^0.17.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_icon.png
    - assets/images/store_icon.png
    - assets/images/google_icon.png
    - assets/images/light.jpg
    - assets/images/appreciate.jpeg
    - assets/images/bow.jpg
    - assets/images/heart.jpeg
    - assets/images/master.jpg
    - assets/images/bible_in_one_year.jpg
    - assets/images/without_distractions.jpg
    - assets/images/pray.jpg
    - assets/images/study.jpg
    - assets/images/secret_place_Store_icon.png
    - assets/esv.json
    - assets/translations.json
    - assets/images/man_kneeling_1.png
    - assets/images/SecretPlace(1024).png
    - assets/images/secret_place_logo_white_background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NewYork
      fonts:
        - asset: fonts/NewYork.ttf
        - asset: fonts/NewYorkItalic.ttf
          style: italic
        - asset: fonts/NewYork.ttf
          weight: 800
    - family: Palatino
      fonts:
        - asset: fonts/pala.ttf
        - asset: fonts/palab.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
import_sorter:
  comments: false
